#!perl

use v5.34;

use Carp;
use CSAF::Util qw(tracking_id_to_well_filename);
use CSAF;
use Getopt::Long;
use Log::Any::Adapter ('Stderr');
use Mojo::File qw(curfile);
use Mojo::Log;
use Mojo::UserAgent;
use Mojo::Util qw(trim);
use Net::NVD;
use URI::PackageURL;
use URI::VersionRange;

# TODO
# In upcoming CSAF 2.1, are permitted multiple PURLs definition in single product_identification_helper
# Get all CPAN ID for all affected version (use $vers->contains) and create a valid CPAN type PURL

#<<<
my $CPANSA_URL   = 'https://raw.githubusercontent.com/briandfoy/cpan-security-advisory/refs/heads/master/cpan-security-advisory.json';
my $CSAF_BASEURL = 'https://raw.githubusercontent.com/giterlizzi/perl-CPANSA-CSAF/develop/csaf/white';
#>>>

my @ERRORS = ();

my %COMPARATOR_DECODE = (
    '='  => 'equal',
    '<'  => 'less than',
    '<=' => 'less than or equal',
    '>'  => 'greater than',
    '>=' => 'greater than or equal',
);

my %options = (force => 0);
GetOptions(\%options, 'dist=s', 'force', 'cpansa=s') or Carp::croak 'Error in CLI arguments';

my $output_directory = curfile->dirname->sibling('csaf/white');

my $log = Mojo::Log->new;

my $nvd = Net::NVD->new(api_key => $ENV{NVD_API_KEY});

my $cpansa = cpan_security_advisories();

unless (%{$cpansa}) {
    Carp::croak 'CPANSA DB missing';
}

my $TOTAL = scalar(keys %{$cpansa->{dists}});

$log->info('CSAF version:',            $CSAF::VERSION);
$log->info('URI::PackageURL version:', $URI::PackageURL::VERSION);
$log->info('CPANSA release:',          $cpansa->{meta}->{date});
$log->info('Distributions in CPANSA:', $TOTAL);

my $index_file = $output_directory->child('index.txt');

my $user_dist = shift;

DIST: foreach my $dist (sort keys %{$cpansa->{dists}}) {

    state $idx;

    $idx++;

    if (my $user_dist = $options{dist}) {
        next DIST if ($dist !~ /^$user_dist$/i);
    }

    $log->info(qq{[$idx/$TOTAL] Process "$dist" distribution});

    my $main_module = $cpansa->{dists}{$dist}{main_module};

    foreach my $advisory (@{$cpansa->{dists}{$dist}{advisories}}) {

        my @affected_packages = ();
        my @fixed_packages    = ();
        my @references        = ();

        my $advisory_id = $advisory->{id};
        my $csaf_id     = tracking_id_to_well_filename($advisory_id);

        next if (defined $options{cpansa} && $advisory_id ne $options{cpansa});

        unless ($advisory->{reported}) {
            push @ERRORS, {type => 'CSAF', message => 'Missing reported date', file => $csaf_id, id => $advisory_id};
            next;
        }

        if ($options{force} == 0 && $index_file->slurp =~ /$csaf_id/) {
            $log->debug("CSAF $csaf_id already processed... skip");
            next;
        }

        my $published_date    = eval { Time::Piece->strptime($advisory->{reported}, '%Y-%m-%d') };
        my $csaf_url          = join '/', $CSAF_BASEURL, $published_date->year, $csaf_id;
        my $description       = trim($advisory->{description});
        my $severity          = $advisory->{severity};
        my $title             = join ' ', $dist, 'vulnerability';
        my $author            = undef;
        my @cves              = @{$advisory->{cves}};
        my @affected_versions = ();
        my @fixed_versions    = ();

        if ($advisory->{affected_versions}) {
            if (ref($advisory->{affected_versions}) ne 'ARRAY') {
                @affected_versions = ($advisory->{affected_versions});
            }
            else {
                @affected_versions = @{$advisory->{affected_versions}};
            }
        }

        if ($advisory->{fixed_versions}) {
            if (ref($advisory->{fixed_versions}) ne 'ARRAY') {
                @fixed_versions = ($advisory->{fixed_versions});
            }
            else {
                @fixed_versions = @{$advisory->{fixed_versions}};
            }
        }

        next if (!$advisory->{affected_versions} && !$advisory->{fixed_versions});
        next unless $advisory->{reported};


        my $csaf = CSAF->new;

        $csaf->document->title($title);
        $csaf->document->lang('en');

        $csaf->document->category('csaf_security_advisory');
        $csaf->document->category('csaf_informational_advisory') if (!@cves);

        $csaf->document->aggregate_severity(text => $severity);

        $csaf->document->notes->item(
            category => 'description',
            title    => 'Vulnerability Description',
            text     => $description
        );

        # $csaf->document->publisher(
        #     category        => 'other',
        #     name            => 'CPAN Security WG',
        #     namespace       => 'https://security.metacpan.org/',
        #     contact_details => 'cpan-security@perl.org'
        # );

        $csaf->document->publisher(
            category        => 'other',
            name            => 'giterlizzi',
            namespace       => 'https://github.com/giterlizzi/',
            contact_details => 'gdt@cpan.org'
        );

        my $tracking = $csaf->document->tracking(
            id                   => $advisory_id,
            status               => 'final',
            version              => '1',
            current_release_date => $published_date,
            initial_release_date => $published_date,
        );

        my $purl = URI::PackageURL->new(type => 'cpan', name => $dist, validation => 0);

        $tracking->revision_history->item(date => $published_date, summary => 'First release', number => '1');

        $csaf->document->references->item(url => $csaf_url, category => 'self', summary => "$advisory_id JSON");

        foreach my $reference (@{$advisory->{references}}) {
            $csaf->document->references->item(url => $reference, summary => $reference, category => 'external');
        }

        if (@affected_versions || @fixed_versions) {

            my $branches         = $csaf->product_tree->branches;
            my $product_item     = $branches->item(category => 'product_name', name => $dist);
            my $product_branches = $product_item->branches;

            my $product_idx = 1;

            foreach my $affected_version (@affected_versions) {

                my $vers_range
                    = URI::VersionRange->new(scheme => 'cpan', constraints => [split(',', $affected_version)]);

                my $product_id   = sprintf('CSAFPID-%04d', $product_idx++);
                my $vers_to_name = vers_to_name(split(',', $affected_version));

                push @affected_packages, $product_id;

                $product_branches->item(
                    category => 'product_version_range',
                    name     => $vers_range,
                    product  => {
                        product_id                    => $product_id,
                        name                          => sprintf('%s %s', $dist, $vers_to_name),
                        product_identification_helper => {purl => $purl}
                    }
                );

            }

            foreach my $fixed_version (@fixed_versions) {

                my $vers_range = URI::VersionRange->new(scheme => 'cpan', constraints => [split(',', $fixed_version)]);

                my $product_id   = sprintf('CSAFPID-%04d', $product_idx++);
                my $vers_to_name = vers_to_name(split(',', $fixed_version));

                push @fixed_packages, $product_id;

                $product_branches->item(
                    category => 'product_version_range',
                    name     => $vers_range,
                    product  => {
                        product_id                    => $product_id,
                        name                          => sprintf('%s %s', $dist, $vers_to_name),
                        product_identification_helper => {purl => $purl}
                    }
                );

            }

        }

        my $vulns = $csaf->vulnerabilities;

        foreach my $cve (@cves) {

            # Add CVE link
            $csaf->document->references->item(
                url      => "https://nvd.nist.gov/vuln/detail/$cve",
                category => 'external',
                summary  => "$cve (NVD)"
            );

            my $cve_data = eval { $nvd->get($cve) };

            if ($@) {
                push @ERRORS, {type => 'Error in Net::NVD', message => $@, file => $dist, id => $advisory_id};
                next;
            }

            my $weakness = $cve_data->{weaknesses} ? $cve_data->{weaknesses}[0]->{description}[0]->{value} : undef;

            my $vuln = $vulns->item(cve => $cve);

            $vuln->cwe(id => $weakness) if $weakness =~ /CWE-\d{2,}/;

            $vuln->product_status->fixed(\@fixed_packages);
            $vuln->product_status->known_affected(\@affected_packages);

            $vuln->notes->item(
                category => 'description',
                title    => 'Vulnerability Description',
                text     => trim($cve_data->{descriptions}[0]{value})
            );

            my $cvss2  = $cve_data->{metrics}->{cvssMetricV2};
            my $cvss30 = $cve_data->{metrics}->{cvssMetricV30};
            my $cvss31 = $cve_data->{metrics}->{cvssMetricV31};

            if (($cvss2 || $cvss30 || $cvss31) && @affected_packages) {

                my $scores = {products => \@affected_packages};

                if ($cvss2) {
                    my $cvss2_base_score    = sprintf('%.1f', $cvss2->[0]->{cvssData}->{baseScore});
                    my $cvss2_vector_string = $cvss2->[0]->{cvssData}->{vectorString};
                    my $cvss2_base_severity = $cvss2->[0]->{baseSeverity};

                    $scores->{cvss_v2} = {
                        baseSeverity => $cvss2_base_severity,
                        baseScore    => $cvss2_base_score,
                        vectorString => $cvss2_vector_string
                    };
                }

                if ($cvss30) {
                    my $cvss30_base_score    = sprintf('%.1f', $cvss30->[0]->{cvssData}->{baseScore});
                    my $cvss30_vector_string = $cvss30->[0]->{cvssData}->{vectorString};
                    my $cvss30_version       = $cvss30->[0]->{cvssData}->{version};
                    my $cvss30_base_severity = $cvss30->[0]->{cvssData}->{baseSeverity};

                    $scores->{cvss_v3} = {
                        version      => $cvss30_version,
                        baseSeverity => $cvss30_base_severity,
                        baseScore    => $cvss30_base_score,
                        vectorString => $cvss30_vector_string
                    };
                }

                if ($cvss31) {
                    my $cvss31_base_score    = sprintf('%.1f', $cvss31->[0]->{cvssData}->{baseScore});
                    my $cvss31_vector_string = $cvss31->[0]->{cvssData}->{vectorString};
                    my $cvss31_version       = $cvss31->[0]->{cvssData}->{version};
                    my $cvss31_base_severity = $cvss31->[0]->{cvssData}->{baseSeverity};

                    $scores->{cvss_v3} = {
                        version      => $cvss31_version,
                        baseSeverity => $cvss31_base_severity,
                        baseScore    => $cvss31_base_score,
                        vectorString => $cvss31_vector_string
                    };
                }

                $vuln->scores->item(%{$scores});

            }

            sleep 6 unless defined $ENV{NVD_API_KEY};
            sleep 2;

        }

        eval {
            my $writer = $csaf->writer(directory => $output_directory->to_string);
            $writer->write;
        };

        if ($@) {
            push @ERRORS, {type => 'Error in CSAF::Write', message => $@, file => $csaf_url, id => $advisory_id};
            Carp::carp($@);
        }

    }
}

if (@ERRORS) {

    say "\n\nErrors:";

    foreach my $error (@ERRORS) {
        say sprintf '- %s -- %s (%s => %s)', $error->{type}, $error->{message}, $error->{file}, $error->{id};
    }

}


sub vers_to_name {

    my @output = ();

    foreach my $version (@_) {

        if ($version =~ /^(>=|<=|=|<|>)(.*)/) {

            my $comparator = $1;
            my $version    = $2;

            my $comparator_name = $COMPARATOR_DECODE{$comparator};

            push @output, "$comparator_name $version";

        }

    }

    return join ' and ', @output;

}


sub cpan_security_advisories {

    if (eval "require CPANSA::DB; 1") {
        return CPANSA::DB->db();
    }

    $log->debug("Fetch CPANSA from $CPANSA_URL");

    my $res = Mojo::UserAgent->new->get($CPANSA_URL)->res;
    return $res->json;

}
